/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v2/admin/signin': {
    post: {
      parameters: {
        body: {
          data: {
            /** @example example@test.com */
            username?: string;
            /** @example example */
            password?: string;
          };
        };
      };
      responses: {
        /** 登入成功 */
        200: {
          schema: definitions['adminSignin'];
        };
        /** Bad Request */
        400: unknown;
      };
    };
  };
  '/v2/logout': {
    post: {
      parameters: {};
      responses: {
        /** 登出成功 */
        200: unknown;
        /** Bad Request */
        400: unknown;
      };
    };
  };
  '/v2/api/user/check': {
    post: {
      parameters: {};
      responses: {
        /** 登入成功 */
        200: {
          schema: definitions['checkLoginAuth'];
        };
        /** 重新登入 */
        403: {
          schema: definitions['checkLoginError'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/products/all': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getProductsAll'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/products': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
          category?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getProducts'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/product': {
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              /** @example [賣]動物園造型衣服3 */
              title?: string;
              /** @example 衣服2 */
              category?: string;
              /** @example 100 */
              origin_price?: number;
              /** @example 300 */
              price?: number;
              /** @example 個 */
              unit?: string;
              /** @example Sit down please 名設計師設計 */
              description?: string;
              /** @example 這是內容 */
              content?: string;
              /** @example 1 */
              is_enabled?: number;
              /** @example 主圖網址 */
              imageUrl?: string;
              /**
               * @example [
               *   "圖片網址一",
               *   "圖片網址二",
               *   "圖片網址三",
               *   "圖片網址四",
               *   "圖片網址五"
               * ]
               */
              imagesUrl?: string[];
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已建立產品 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example imagesUrl 格式不正確 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/product/{id}': {
    put: {
      parameters: {
        path: {
          api_path: string;
          /** 要修改的 ID */
          id: string;
        };
        body: {
          data: {
            data?: {
              /** @example [賣]動物園造型衣服3 */
              title?: string;
              /** @example 衣服2 */
              category?: string;
              /** @example 100 */
              origin_price?: number;
              /** @example 300 */
              price?: number;
              /** @example 個 */
              unit?: string;
              /** @example Sit down please 名設計師設計 */
              description?: string;
              /** @example 這是內容 */
              content?: string;
              /** @example 1 */
              is_enabled?: number;
              /** @example 主圖網址 */
              imageUrl?: string;
              /**
               * @example [
               *   "圖片網址一",
               *   "圖片網址二",
               *   "圖片網址三",
               *   "圖片網址四",
               *   "圖片網址五"
               * ]
               */
              imagesUrl?: string[];
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已更新產品 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example title 屬性不得為空 */
            message?: string;
          };
        };
        /** Not Found */
        404: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example id 不存在 */
            message?: string;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          api_path: string;
          /** 要刪除的 ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已刪除產品 */
            message?: string;
          };
        };
        /** Forbidden */
        403: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example 無此權限 */
            message?: string;
          };
        };
        /** Not Found */
        404: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example 找不到產品 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/orders': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getOrders'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/order/{id}': {
    put: {
      parameters: {
        path: {
          api_path: string;
          /** 要修改的 ID */
          id: string;
        };
        body: {
          data: {
            data?: {
              /** @example 1523539519 */
              create_at?: number;
              /** @example false */
              is_paid?: boolean;
              /** @example 這是留言 */
              message?: string;
              products?: {
                L8nBrq8Ym4ARI1Kog4t?: {
                  /** @example L8nBrq8Ym4ARI1Kog4t */
                  id?: string;
                  /** @example -L8moRfPlDZZ2e-1ritQ */
                  product_id?: string;
                  /** @example 3 */
                  qty?: string;
                };
              };
              user?: {
                /** @example kaohsiung */
                address?: string;
                /** @example test@gmail.com */
                email?: string;
                /** @example test */
                name?: string;
                /** @example 0912346768 */
                tel?: string;
              };
              /** @example 2 */
              num?: number;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['updateOrderById'];
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example title 屬性不得為空 */
            message?: string;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          api_path: string;
          /** 要修改的 ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['removeOrdersByOrderId'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/orders/all': {
    delete: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['removeAllOrders'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/coupon': {
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              /** @example 超級特惠價格 */
              title?: string;
              /** @example 1 */
              is_enabled?: number;
              /** @example 80 */
              percent?: number;
              /** @example 1555459200 */
              due_date?: number;
              /** @example testCode */
              code?: string;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已建立產品 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example imagesUrl 格式不正確 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/coupon/{id}': {
    put: {
      parameters: {
        path: {
          api_path: string;
          /** 要修改的 ID */
          id: string;
        };
        body: {
          data: {
            data?: {
              /** @example 超級特惠價格2 */
              title?: string;
              /** @example 1 */
              is_enabled?: number;
              /** @example 70 */
              percent?: number;
              /** @example 1555459200 */
              due_date?: number;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已更新產品 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example title 屬性不得為空 */
            message?: string;
          };
        };
        /** Not Found */
        404: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example id 不存在 */
            message?: string;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          api_path: string;
          /** 要刪除的 ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已刪除優惠券 */
            message?: string;
          };
        };
        /** Not Found */
        404: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example 找不到優惠券 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/coupons': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getCoupons'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/upload': {
    /** 表單上傳<br/>  <p>請注意，僅限使用 jpg、jpeg 與 png 格式，檔案大小限制為 3MB 以下。</p>  <pre>  <code>  &lt;form action="/api/thisismycourse2/admin/upload" enctype="multipart/form-data"  method="post"&gt;<br/>  &lt;input type="file" name="file-to-upload"&gt;<br/>  &lt;input type="submit" value="Upload"&gt;<br/>  &lt;/form&gt;  </code>  </pre> */
    post: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** 上傳成功 */
        200: {
          schema: definitions['uploadSuccess'];
        };
        /** 上傳失敗 */
        400: {
          schema: definitions['uploadError'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/articles': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getArticles'];
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/article/{id}': {
    get: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['getArticleById'];
        };
      };
    };
    put: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
        body: {
          data: {
            data?: {
              /** @example 新增第一篇文章2 */
              title?: string;
              /** @example 文章內容2 */
              description?: string;
              /** @example test.testtest */
              image?: string;
              /**
               * @example [
               *   "tag1"
               * ]
               */
              tag?: string[];
              /** @example 1234566 */
              create_at?: number;
              /** @example alice */
              author?: string;
              /** @example false */
              isPublic?: boolean;
              /** @example 這是內容 */
              content?: string;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已建立文章 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example title 屬性不得為空 */
            message?: string;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          api_path: string;
          /** 要刪除的 ID */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已刪除文章 */
            message?: string;
          };
        };
        /** Not Found */
        404: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example 找不到文章 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/admin/article': {
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              /** @example 新增第一篇文章 */
              title?: string;
              /** @example 文章內容 */
              description?: string;
              /** @example test.testtest */
              image?: string;
              /**
               * @example [
               *   "tag1"
               * ]
               */
              tag?: string[];
              /** @example 1555459220 */
              create_at?: number;
              /** @example alice */
              author?: string;
              /** @example false */
              isPublic?: boolean;
              /** @example 這是內容 */
              content?: string;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: {
            /** @example true */
            success?: boolean;
            /** @example 已建立文章 */
            message?: string;
          };
        };
        /** Bad Request */
        400: {
          schema: {
            /** @example false */
            success?: boolean;
            /** @example title 屬性不得為空 */
            message?: string;
          };
        };
      };
    };
  };
  '/v2/api/{api_path}/products/all': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userProductsAll'];
        };
      };
    };
  };
  '/v2/api/{api_path}/products': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
          category?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userProductsAll'];
        };
      };
    };
  };
  '/v2/api/{api_path}/product/{id}': {
    get: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userProduct'];
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: unknown;
      };
    };
  };
  '/v2/api/{api_path}/cart': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetCarts'];
        };
      };
    };
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              /** @example -L9tH8jxVb2Ka_DYPwng */
              product_id?: string;
              /** @example 1 */
              qty?: number;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userAddCart'];
        };
      };
    };
  };
  '/v2/api/{api_path}/cart/{id}': {
    put: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
        body: {
          data: {
            data?: {
              /** @example -L9tH8jxVb2Ka_DYPwng */
              product_id?: string;
              /** @example 1 */
              qty?: number;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userUpdateCart'];
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userDeleteCart'];
        };
      };
    };
  };
  '/v2/api/{api_path}/carts': {
    delete: {
      parameters: {
        path: {
          api_path: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userDeleteCartAll'];
        };
        /** Bad Request */
        400: unknown;
      };
    };
  };
  '/v2/api/{api_path}/coupon': {
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              /** @example testCode */
              code?: string;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userApplyCoupon'];
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: unknown;
      };
    };
  };
  '/v2/api/{api_path}/order': {
    post: {
      parameters: {
        path: {
          api_path: string;
        };
        body: {
          data: {
            data?: {
              user?: {
                /** @example test */
                name?: string;
                /** @example test@gmail.com */
                email?: string;
                /** @example 0912346768 */
                tel?: string;
                /** @example kaohsiung */
                address?: string;
              };
              /** @example 這是留言 */
              message?: string;
            };
          };
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userCheckoutOrder'];
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: unknown;
      };
    };
  };
  '/v2/api/{api_path}/orders': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetOrders'];
        };
      };
    };
  };
  '/v2/api/{api_path}/order/{order_id}': {
    get: {
      parameters: {
        path: {
          api_path: string;
          order_id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetOrder'];
        };
      };
    };
  };
  '/v2/api/{api_path}/pay/{order_id}': {
    post: {
      parameters: {
        path: {
          api_path: string;
          order_id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetOrder'];
        };
      };
    };
  };
  '/v2/api/{api_path}/articles': {
    get: {
      parameters: {
        path: {
          api_path: string;
        };
        query: {
          page?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetArticles'];
        };
      };
    };
  };
  '/v2/api/{api_path}/article/{id}': {
    get: {
      parameters: {
        path: {
          api_path: string;
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['userGetArticles'];
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: unknown;
      };
    };
  };
}

export interface definitions {
  adminSignin: {
    /** @example true */
    success?: boolean;
    /** @example true */
    status?: boolean;
    /** @example 登入成功 */
    message?: string;
    /** @example QZDQO0zht4MNp7CE2t1 */
    uid?: string;
    /** @example eyJhbGciOiJSUzI1NiIsImtpZCI6InRCME0yQSJ9.... */
    token?: string;
    /** @example 1630734430297 */
    expired?: number;
  };
  checkLoginAuth: {
    /** @example true */
    success?: boolean;
    message?: string;
    /** @example QZDQO0zht4MNp7CE2t1 */
    uid?: string;
  };
  checkLoginError: {
    /** @example false */
    success?: boolean;
    /** @example 請重新登入 */
    message?: string;
  };
  uploadSuccess: {
    /** @example true */
    success?: boolean;
    /** @example 圖片連結(https) */
    imageUrl?: string;
  };
  uploadError: {
    /** @example false */
    success?: boolean;
    /** @example 檔案格式錯誤 */
    message?: string;
  };
  storageErrors: {
    /** @example false */
    success?: boolean;
    message?: {
      /** @example LIMIT_FILE_SIZE */
      code?: string;
      /** @example file-to-upload */
      field?: string;
      /** @example [] */
      storageErrors?: unknown[];
    };
  };
  getProductsAll: {
    /** @example true */
    success?: boolean;
    products?: {
      '-L9tH8jxVb2Ka_DYPwng'?: {
        /** @example 衣服3 */
        category?: string;
        /** @example 這是內容 */
        content?: string;
        /** @example Sit down please 名設計師設計 */
        description?: string;
        /** @example -L9tH8jxVb2Ka_DYPwng */
        id?: string;
        /** @example 1 */
        is_enabled?: number;
        /** @example 1 */
        num?: number;
        /** @example 500 */
        origin_price?: number;
        /** @example 600 */
        price?: number;
        /** @example [賣]動物園造型衣服3 */
        title?: string;
        /** @example 個 */
        unit?: string;
        /** @example 主圖網址 */
        imageUrl?: string;
        /**
         * @example [
         *   "圖片網址一",
         *   "圖片網址二",
         *   "圖片網址三",
         *   "圖片網址四",
         *   "圖片網址五"
         * ]
         */
        imagesUrl?: string[];
      };
    };
  };
  getProducts: {
    /** @example true */
    success?: boolean;
    products?: {
      /** @example 衣服2 */
      category?: string;
      /** @example 這是內容 */
      content?: string;
      /** @example Sit down please 名設計師設計 */
      description?: string;
      /** @example -L9tH8jxVb2Ka_DYPwng */
      id?: string;
      /** @example 1 */
      is_enabled?: number;
      /** @example 100 */
      origin_price?: number;
      /** @example 600 */
      price?: number;
      /** @example [賣]動物園造型衣服3 */
      title?: string;
      /** @example 個 */
      unit?: string;
      /** @example 1 */
      num?: number;
      /** @example 主圖網址 */
      imageUrl?: string;
      /**
       * @example [
       *   "圖片網址一",
       *   "圖片網址二",
       *   "圖片網址三",
       *   "圖片網址四",
       *   "圖片網址五"
       * ]
       */
      imagesUrl?: string[];
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  userProducts: {
    /** @example true */
    success?: boolean;
    products?: {
      '-L9tH8jxVb2Ka_DYPwng'?: {
        /** @example 衣服3 */
        category?: string;
        /** @example 這是內容 */
        content?: string;
        /** @example Sit down please 名設計師設計 */
        description?: string;
        /** @example -L9tH8jxVb2Ka_DYPwng */
        id?: string;
        /** @example 1 */
        is_enabled?: number;
        /** @example 1 */
        num?: number;
        /** @example 500 */
        origin_price?: number;
        /** @example 600 */
        price?: number;
        /** @example [賣]動物園造型衣服3 */
        title?: string;
        /** @example 個 */
        unit?: string;
        /** @example 主圖網址 */
        imageUrl?: string;
        /**
         * @example [
         *   "圖片網址一",
         *   "圖片網址二",
         *   "圖片網址三",
         *   "圖片網址四",
         *   "圖片網址五"
         * ]
         */
        imagesUrl?: string[];
      };
    };
    /** @example [] */
    messages?: unknown[];
  };
  userProduct: {
    /** @example true */
    success?: boolean;
    product?: {
      /** @example 衣服3 */
      category?: string;
      /** @example 這是內容 */
      content?: string;
      /** @example Sit down please 名設計師設計 */
      description?: string;
      /** @example -L9tH8jxVb2Ka_DYPwng */
      id?: string;
      /** @example 主圖網址 */
      imageUrl?: string;
      /**
       * @example [
       *   "圖片網址一",
       *   "圖片網址二",
       *   "圖片網址三",
       *   "圖片網址四",
       *   "圖片網址五"
       * ]
       */
      imagesUrl?: string[];
      /** @example 1 */
      is_enabled?: number;
      /** @example 1 */
      num?: number;
      /** @example 100 */
      origin_price?: number;
      /** @example 600 */
      price?: number;
      /** @example [賣]動物園造型衣服3 */
      title?: string;
      /** @example 個 */
      unit?: string;
    };
  };
  userProductsAll: {
    /** @example true */
    success?: boolean;
    products?: {
      /** @example 衣服3 */
      category?: string;
      /** @example 這是內容 */
      content?: string;
      /** @example Sit down please 名設計師設計 */
      description?: string;
      /** @example -L9tH8jxVb2Ka_DYPwng */
      id?: string;
      /** @example 主圖網址 */
      imageUrl?: string;
      /**
       * @example [
       *   "圖片網址一",
       *   "圖片網址二",
       *   "圖片網址三",
       *   "圖片網址四",
       *   "圖片網址五"
       * ]
       */
      imagesUrl?: string[];
      /** @example 1 */
      is_enabled?: number;
      /** @example 1 */
      num?: number;
      /** @example 100 */
      origin_price?: number;
      /** @example 600 */
      price?: number;
      /** @example [賣]動物園造型衣服3 */
      title?: string;
      /** @example 個 */
      unit?: string;
    }[];
    /** @example [] */
    messages?: unknown[];
  };
  getOrders: {
    /** @example true */
    success?: boolean;
    orders?: {
      /** @example 1523539519 */
      create_at?: number;
      /** @example -L9u11NAE0m0SpSBUDIq */
      id?: string;
      /** @example false */
      is_paid?: boolean;
      /** @example 這是留言 */
      message?: string;
      products?: {
        L8nBrq8Ym4ARI1Kog4t?: {
          /** @example L8nBrq8Ym4ARI1Kog4t */
          id?: string;
          /** @example -L8moRfPlDZZ2e-1ritQ */
          product_id?: string;
          /** @example 3 */
          qty?: string;
        };
      };
      user?: {
        /** @example kaohsiung */
        address?: string;
        /** @example test@gmail.com */
        email?: string;
        /** @example test */
        name?: string;
        /** @example 0912346768 */
        tel?: string;
      };
      /** @example 2 */
      num?: number;
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  updateOrderById: {
    /** @example true */
    success?: boolean;
    /** @example 已更新訂單資訊 */
    message?: string;
  };
  removeOrdersByOrderId: {
    /** @example true */
    success?: boolean;
    /** @example 已刪除 */
    message?: string;
  };
  removeAllOrders: {
    /** @example true */
    success?: boolean;
    /** @example 已刪除 */
    message?: string;
  };
  getCoupons: {
    /** @example true */
    success?: boolean;
    coupons?: {
      /** @example 6547658 */
      due_date?: number;
      /** @example 1 */
      is_enabled?: number;
      /** @example 80 */
      percent?: number;
      /** @example 超級特惠價格 */
      title?: string;
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  userApplyCoupon: {
    /** @example true */
    success?: boolean;
    /** @example 已套用優惠券:testCode */
    message?: string;
    data?: {
      /** @example 2160 */
      final_total?: number;
    };
  };
  getArticles: {
    /** @example true */
    success?: boolean;
    articles?: {
      /** @example alice */
      author?: string;
      /** @example 123455 */
      create_at?: number;
      /** @example 123 */
      description?: string;
      /** @example -MT-RbUo-e-d3RZIS_kJ */
      id?: string;
      /** @example url123 */
      image?: string;
      /** @example false */
      isPublic?: boolean;
      /**
       * @example [
       *   "tag1",
       *   "tag2"
       * ]
       */
      tag?: string[];
      /** @example title1234 */
      title?: string;
      /** @example 1 */
      num?: number;
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  getArticleById: {
    /** @example true */
    success?: boolean;
    article?: {
      /** @example alice */
      author?: string;
      /** @example 123455 */
      create_at?: number;
      /** @example 123 */
      description?: string;
      /** @example -MT-RbUo-e-d3RZIS_kJ */
      id?: string;
      /** @example <p>你一現出，社這邊是是因為你真是。比較第一次開可以</p> */
      content?: string;
      /** @example url123 */
      image?: string;
      /** @example false */
      isPublic?: boolean;
      /**
       * @example [
       *   "tag1",
       *   "tag2"
       * ]
       */
      tag?: string[];
      /** @example title1234 */
      title?: string;
      /** @example 1 */
      num?: number;
    };
  };
  userGetArticles: {
    /** @example true */
    success?: boolean;
    articles?: {
      /** @example 新增第一篇文章 */
      title?: string;
      /** @example 文章內容 */
      description?: string;
      /** @example test.testtest */
      image?: string;
      /**
       * @example [
       *   "tag1"
       * ]
       */
      tag?: string[];
      /** @example 1555459220 */
      create_at?: number;
      /** @example alice */
      author?: string;
      /** @example false */
      isPublic?: boolean;
      /** @example 這是內容 */
      content?: string;
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  userGetArticle: {
    /** @example true */
    success?: boolean;
    article?: {
      /** @example 新增第一篇文章 */
      title?: string;
      /** @example 文章內容 */
      description?: string;
      /** @example test.testtest */
      image?: string;
      /**
       * @example [
       *   "tag1"
       * ]
       */
      tag?: string[];
      /** @example <p>你一現出，社這邊是是因為你真是。比較第一次開可以</p> */
      content?: string;
      /** @example 1555459220 */
      create_at?: number;
      /** @example alice */
      author?: string;
      /** @example false */
      isPublic?: boolean;
    };
  };
  userAddCart: {
    /** @example true */
    success?: boolean;
    /** @example 已加入購物車 */
    message?: string;
    data?: {
      /** @example -L9tH8jxVb2Ka_DYPwng */
      product_id?: string;
      /** @example 1 */
      qty?: number;
      /** @example -LAl5v_2MhWeh3linQxx */
      id?: string;
      /** @example 600 */
      total?: number;
      /** @example 600 */
      final_total?: number;
      product?: {
        /** @example 衣服3 */
        category?: string;
        /** @example 這是內容 */
        content?: string;
        /** @example Sit down please 名設計師設計 */
        description?: string;
        /** @example -L9tH8jxVb2Ka_DYPwng */
        id?: string;
        /** @example 主圖網址 */
        imageUrl?: string;
        /**
         * @example [
         *   "圖片網址一",
         *   "圖片網址二",
         *   "圖片網址三",
         *   "圖片網址四",
         *   "圖片網址五"
         * ]
         */
        imagesUrl?: string[];
        /** @example 1 */
        is_enabled?: number;
        /** @example 1 */
        num?: number;
        /** @example 500 */
        origin_price?: number;
        /** @example 600 */
        price?: number;
        /** @example [賣]動物園造型衣服3 */
        title?: string;
        /** @example 個 */
        unit?: string;
      };
    };
  };
  userGetCarts: {
    /** @example true */
    success?: boolean;
    data?: {
      carts?: {
        coupon?: {
          /** @example testCode */
          code?: string;
          /** @example 6547658 */
          due_date?: number;
          /** @example -L9uIs5EfPibJpwwTMhN */
          id?: string;
          /** @example 1 */
          is_enabled?: number;
          /** @example 60 */
          percent?: number;
          /** @example 超級特惠價格 */
          title?: string;
        };
        /** @example 2160 */
        final_total?: number;
        /** @example -LATwxc_bIJu-AR4AlNj */
        id?: string;
        product?: {
          /** @example 衣服3 */
          category?: string;
          /** @example 這是內容 */
          content?: string;
          /** @example Sit down please 名設計師設計 */
          description?: string;
          /** @example -L9tH8jxVb2Ka_DYPwng */
          id?: string;
          /** @example 主圖網址 */
          imageUrl?: string;
          /**
           * @example [
           *   "圖片網址一",
           *   "圖片網址二",
           *   "圖片網址三",
           *   "圖片網址四",
           *   "圖片網址五"
           * ]
           */
          imagesUrl?: string[];
          /** @example 1 */
          is_enabled?: number;
          /** @example 1 */
          num?: number;
          /** @example 500 */
          origin_price?: number;
          /** @example 600 */
          price?: number;
          /** @example [賣]動物園造型衣服3 */
          title?: string;
          /** @example 個 */
          unit?: string;
        };
        /** @example -L9tH8jxVb2Ka_DYPwng */
        product_id?: string;
        /** @example 6 */
        qty?: number;
        /** @example 3600 */
        total?: number;
      }[];
      /** @example 3600 */
      total?: number;
      /** @example 2160 */
      final_total?: number;
    };
    /** @example [] */
    messages?: unknown[];
  };
  userDeleteCart: {
    /** @example true */
    success?: boolean;
    /** @example 已刪除 */
    message?: string;
  };
  userDeleteCartAll: {
    /** @example true */
    success?: boolean;
    /** @example 已刪除 */
    message?: string;
  };
  userUpdateCart: {
    /** @example true */
    success?: boolean;
    /** @example 已更新購物車 */
    message?: string;
    data?: {
      /** @example -L9tH8jxVb2Ka_DYPwng */
      product_id?: string;
      /** @example 1 */
      qty?: number;
    };
  };
  userCheckoutOrder: {
    /** @example true */
    success?: boolean;
    /** @example 已建立訂單 */
    message?: string;
    /** @example 100 */
    total?: number;
    /** @example 1523539519 */
    create_at?: number;
    /** @example -L9tH8jxVb2Ka_DYPwng */
    orderId?: string;
  };
  userGetOrders: {
    /** @example true */
    success?: boolean;
    orders?: {
      /** @example 1523539519 */
      create_at?: number;
      /** @example -L9u11NAE0m0SpSBUDIq */
      id?: string;
      /** @example false */
      is_paid?: boolean;
      /** @example 這是留言 */
      message?: string;
      products?: {
        /** @example L8nBrq8Ym4ARI1Kog4t */
        id?: string;
        /** @example -L8moRfPlDZZ2e-1ritQ */
        product_id?: string;
        /** @example 3 */
        qty?: string;
      }[];
      user?: {
        /** @example kaohsiung */
        address?: string;
        /** @example test@gmail.com */
        email?: string;
        /** @example test */
        name?: string;
        /** @example 0912346768 */
        tel?: string;
      };
      /** @example 1 */
      num?: number;
    }[];
    pagination?: {
      /** @example 1 */
      total_pages?: number;
      /** @example 1 */
      current_page?: number;
      /** @example false */
      has_pre?: boolean;
      /** @example false */
      has_next?: boolean;
      /** @example */
      category?: string;
    };
    /** @example [] */
    messages?: unknown[];
  };
  userGetOrder: {
    /** @example true */
    success?: boolean;
    order?: {
      /** @example 1523539834 */
      create_at?: number;
      /** @example -L9u2EUkQSoEmW7QzGLF */
      id?: string;
      /** @example false */
      is_paid?: boolean;
      /** @example 這是留言 */
      message?: string;
      products?: {
        /** @example L8nBrq8Ym4ARI1Kog4t */
        id?: string;
        /** @example -L8moRfPlDZZ2e-1ritQ */
        product_id?: string;
        /** @example 3 */
        qty?: string;
      }[];
      /** @example 100 */
      total?: number;
      user?: {
        /** @example kaohsiung */
        address?: string;
        /** @example test@gmail.com */
        email?: string;
        /** @example test */
        name?: string;
        /** @example 0912346768 */
        tel?: string;
      };
    };
  };
  userPayment: {
    /** @example true */
    success?: boolean;
    /** @example 付款完成 */
    message?: string;
  };
}

export interface operations {}

export interface external {}
